services:
  dotnet_server:
    build: 
      context: ./server
      dockerfile: dockerfile
    container_name: dotnet_server
    ports:
      - "5000:8080"
    depends_on:
      - langchain_service

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    profiles: ["live"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  
  # ollama-pull-model:
  #   image: curlimages/curl:latest
  #   container_name: ollama_pull_model
  #   profiles: ["live"]
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #   volumes:
  #     - ./pull-models.sh:/sys/init/pull-models.sh:ro
  #   depends_on:
  #     - ollama
  #   entrypoint: ["/bin/sh", "sys/init/pull-models.sh"]

  langchain_service:
    build: 
      context: ./langchain_service
      dockerfile: dockerfile
    container_name: langchain_service
    ports:
      - "5001:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_MODE=${LLM_MODE:-mock}
      - LLM_MODEL=${LLM_MODEL:-llama3.1:8b}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret_pass}
      - POSTGRES_DB=${POSTGRES_DB:-vectordb}
    depends_on:
      pgvector-service:
        condition: service_healthy

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      #- OPENAI_API_BASE_URL=http://dotnet_server:8080/v1
      - OPENAI_API_BASE_URL=http://langchain_service:8080/v1
      - OPENAI_API_KEY=dummy-key-not-checked
      - ENABLE_OLLAMA_API=false
      - WEBUI_AUTH=false
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      #- dotnet_server
      - langchain_service

  pgvector-service:
    image: pgvector/pgvector:pg16
    container_name: pgvector_service
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret_pass}
      - POSTGRES_DB=${POSTGRES_DB:-vectordb}
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-vectordb}"]
      interval: 5s
      retries: 10
    

volumes:
  ollama_data:
  pgdata:
  openwebui_data:
