#lightweight image that can run my python with Flask server 
#also needs to be able to run langchain libraries
FROM python:3.9.13-slim-buster

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]